Добавления на УРНУ
Relicta-Team/ReSDK_A3.vr pull request #535
Opened 2024-10-22 11:32 UTC by Italovich-Relicta

# Описание
Новая роль, изменения на карте (новое здание, изменения в штабе), сделал потише тревогу.

2024-10-23 07:13 UTC, Yobas commented
Я могу заревьювить в ночь с четверга на пятницу

2024-10-24 23:36 UTC, Yobas requested changes

2024-10-24 23:36 UTC, Yobas commented on Src/host/MapManager/Maps/Army.sqf
Не думаю, что это должно быть здесь
![image](https://github.com/user-attachments/assets/d5091ec3-8b3a-465c-9c8c-b1be50803049)

2024-10-24 23:36 UTC, Yobas commented on ReNode/Graphs/Army/GMArmy.graph
3 часа не много для режима, в котором с 60% вероятностью не будет никаких антагонистов?

2024-10-24 23:36 UTC, Yobas commented on ReNode/Graphs/Army/Roles/RNovobranetsArmy.graph
Вот кусок новобранца. Кровати и точки от 0 до 11
![image](https://github.com/user-attachments/assets/7d3b1698-ec06-4675-b910-2780ccac9eae)
В тоже время старослужащие (кровати от 0 до 1)
![image](https://github.com/user-attachments/assets/2bc8e2e6-b80a-4cc2-a5d2-8847bf2e0bd7)

Тут явно что то не будет работать так как задумано. Насколько мне помнится при запросе позиции значение количества заходов уже уменьшено на единицу. Ты старослужащих проверял, нормально ли они спавнятся на кроватях?

2024-10-25 07:00 UTC, Italovich-Relicta commented on Src/host/MapManager/Maps/Army.sqf
Должно, он там появляется с маленьким шансом и его хер найдешь, если ты не просматривал карту в редакторе (проверял)

2024-10-25 07:01 UTC, Italovich-Relicta commented on ReNode/Graphs/Army/GMArmy.graph
Меня попросили увеличить время режима, потому что на прошлом запуске таймер кончился (плюс всегда есть кнопка для окончания раунда). Можно уменьшить до 2 с половиной часов, но я не уверен

2024-10-25 07:03 UTC, Italovich-Relicta commented on ReNode/Graphs/Army/Roles/RNovobranetsArmy.graph
С старослужащим все нормально должно быть, у него две кровати со значениями 0 и 1. А вот про новобранца спасибо, сейчас исправлю

2024-10-25 14:18 UTC, Yobas requested changes

2024-10-25 14:18 UTC, Yobas commented on Src/host/MapManager/Maps/Army.sqf
Ну ты же его нашёл. Как по мне это нечестное преимущество по отношению к другим игрокам. 
Нахождение там пистолета с точки зрения логики и здравого смысла совершенно не оправдано. Городские карты (пусть и с военным уклоном) не лучшее место для таких нычек. 

Если пистолет нужен для антагониста то заспавни его в одежде этого антагониста. Во-первых, будет азарт что в любой момент могут сделать досмотр и спалить. Во-вторых антагонист при необходимости сам спрячет пистолет в нужном месте, что может дать ветки для различных интересных ситуаций. А с карты давай уберём.

2024-10-25 15:23 UTC, Yobas requested changes
Оружие в свободной доступности на карте

2024-10-25 15:23 UTC, Yobas commented on Src/host/MapManager/Maps/Army.sqf
Похоже по всей карте раскиданы нычки с оружием
![image](https://github.com/user-attachments/assets/804d7108-d73a-408e-990a-e7c7310512f0)

2024-10-25 15:26 UTC, Italovich-Relicta commented on Src/host/MapManager/Maps/Army.sqf
Я их оставлял с маленьким шансом. Я не предполагал что люди найдут это оружие и начнут стрелять по всем. Мне удалять все нычки с огнестрелами?

2024-10-25 15:32 UTC, Yobas commented on Src/host/MapManager/Maps/Army.sqf
Да давай 2 с половой поставим

2024-10-25 15:32 UTC, Yobas commented on ReNode/Graphs/Army/GMArmy.graph
> Меня попросили увеличить время режима, потому что на прошлом запуске таймер кончился (плюс всегда есть кнопка для окончания раунда). Можно уменьшить до 2 с половиной часов, но я не уверен

Да давай 2 с половой поставим

2024-10-25 15:50 UTC, Yobas approved these changes

2024-10-25 15:50 UTC, merged